resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        failAfterMaxAttempts: true
    instances:
      backendA:
        baseConfig: default
        maxAttenpts: 5
      backendB:
        baseConfig: default
  ratelimiter:
    configs:
      default:
        limiteForPeriod: 10
        timeoutDuration: 2s
        limitRefreshPeriod: 5s
    instances:
      backendA:
        baseConfig: default
        limitForPeriod: 2
      backendB:
        baseConfig: default
        timeoutDuration: 0s
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10
        maxWaitDuration: 0
    instances:
      backendA:
        baseConfig: default
        maxConcurrentCalls: 4
      backendB:
        baseConfig: default
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50 # 熔断器打开的失败阈值
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        permittedNumberOfCallsInHalfOpenState: 10
#        maxWaitDurationInHalfOpenState: 0s
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 60000 # 熔断器从打开到半开需要的时间
        automaticTransitionFromOpenToHalfOpenEnabled: false # 是否自动从打开到半开，不需要触发
#        recordFailurePredicate:    com.example.resilience4j.exceptions.RecordFailurePredicate # 熔断器失败判定
#        recordExceptions: # 记录的异常
#        ignoreExceptions: # 忽略的异常
    instances:
      backendA:
        baseConfig: default
        waitDurationInOpenState: 5000
        failureRateThreshold: 20
      backendB:
        baseConfig: default
